dist: trusty
env:
  - GHCVER=7.10.3 CABALVER=1.22
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
install:
  - cabal update
  - cabal install --only-dependencies
before_script:
  - git clone --depth 1 https://github.com/yahoojapan/k2hash.git
  - cd k2hash/ && git submodule update --init --recursive && cd ../
  - cd k2hash/fullock/ && ./autogen.sh && ./configure && make && sudo make install && cd ../../
  - cd k2hash/ && ./autogen.sh && ./configure && sudo make install && cd ../
  - sudo ldconfig
script:
  - cabal build
